version: 2.1
orbs:
  cypress: cypress-io/cypress@1
jobs:
  build-units:
    working_directory: ~/src
    docker:
      - image: cimg/node:16.14.2
    steps:
      - checkout
      - run:
          name: Update NPM
          command: "sudo npm install -g npm"
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: Install Dependencies
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - run:
          name: Lint
          command: npm run lint
      - run:
          name: Run tests
          command: npm run test

workflows:
  build:
    jobs:
      - build-units
      - cypress/install:
          pre-steps:
          - run: npm install ajv-errors@1 
      - cypress/run:
          requires:
            - cypress/install
          start: npm start 
          wait-on: 'http://localhost:3000'
