version: 2.1
orbs:
  cypress: cypress-io/cypress@1
executors:
  with-chrome:
    resource_class: small
    docker:
      - image: "cypress/browsers:node16.14.2-slim-chrome100-ff99-edge"
jobs:
  build-units:
    working_directory: ~/src
    docker:
      - image: cimg/node:16.14.2
    steps:
      - checkout
      - run:
          name: Update NPM
          command: "sudo npm install -g npm"
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: Install Dependencies
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - run:
          name: Lint
          command: npm run lint
      - run:
          name: Run tests
          command: npm run test

workflows:
  build:
    jobs:
      - cypress/install:
          pre-steps:
          - run: npm install -g npm@latest
      - cypress/run:
          requires:
            - cypress/install
          executor: with-chrome
          browser: chrome
          start:
            npm start
          post-steps:
            - run: ls
            - store_test_results:
                path: cypress/results
            - store_artifacts:
                path: cypress/screenshots

