version: 2.1

jobs:
  build-unit-tests:
    working_directory: ~/src
    docker:
      - image: cimg/node:16.14.2
    steps:
      - checkout
      - run:
          name: Update NPM
          command: "sudo npm install -g npm"
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: Install Dependencies
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - run:
          name: Lint
          command: npm run lint
      - run:
          name: Run tests
          command: npm run test

  e2e:
    docker:
      - image: cypress/browsers:node16.14.2-slim-chrome100-ff99-edge
    steps:
      - checkout
      - restore_cache:
          key: e2e-cache-{{ checksum "package.json" }}
      - run:
          name: install ci dependencies
          command: npm install
      - save_cache:
          key: e2e-cache-{{ checksum "package.json" }}
          paths:
            - ~/.npm
            - ~/.cache
      - run:
          name: Launch server
          command: npm start
          background: true
      - run: sleep 45
      - run:
          name: Run E2E tests
          command: npm run cypress:run
      - run: pwd
      - store_test_results:
          path: results
      - store_artifacts:
          path: cypress/videos
      - store_artifacts:
          path: cypress/screenshots

workflows:
  build:
    jobs:
      - build-unit-tests
      - e2e
